console.log(document.getElementsByTagName("div"))
console.log(document.getElementsByTagName("div")[0])
console.log(document.getElementsByTagName("div")[1].innerHTML)
console.log(document.getElementsByTagName("br"))
console.log(document.getElementsByTagName("p"))
console.log(document.querySelector("div"))
console.log(document.querySelector(".div_02"))
console.log(document.querySelector("#paragrafo_02"))