// Browser Object Model (BOM)

console.log(screen.width)
console.log(screen.height)
console.log(screen.orientation)
console.log(screen.orientation.angle)
console.log(screen.orientation.type)
console.log(screen.orientation.onchange)
console.log(navigator)
console.log(location)
console.log(history)