console.log(document.getElementById("fruta"))
console.log(document.getElementById("fruta").innerHTML)
console.log(document.getElementsByClassName("carro"))
console.log(document.getElementsByClassName("carro")[0])
console.log(document.getElementsByClassName("carro")[1])
console.log(document.getElementsByClassName("carro")[2].innerHTML)